### PR TITLE
Upgraded gradle wrapper to 3.1

### PR DESCRIPTION
**Pull request by maringan**
I upgraded gradle wrapper to version 3.1

### CODE REVIEW

**Comment by ghost** [comment]
Your pull request doesn't follow our guidelines. Please fix the following:
- Pull request description cannot be empty [(?)](https://gitmagic.io/rules/#/pull-request/body-cannot-be-empty)
- Pull request title must be in past tense (e.g. "added", "fixed", "changed") [(?)](https://gitmagic.io/rules/#/pull-request/subject-must-be-in-tense)

[Click here](https://app.gitmagic.io/seu-as-code/seu-as-code.archetype/20/b93cf68c-3b42-4503-b043-9246d76504d4/13427d18-68db-4062-a913-864f7a9672ce) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
This pull request still violates some of our guidelines:
- Pull request description cannot be empty [(?)](https://gitmagic.io/rules/#/pull-request/body-cannot-be-empty)

[Click here](https://app.gitmagic.io/seu-as-code/seu-as-code.archetype/20/b93cf68c-3b42-4503-b043-9246d76504d4/13427d18-68db-4062-a913-864f7a9672ce) for details.

**Comment by ghost** [comment]
Thank you, the title and description now looks good! :bowtie:

**Comment by lreimer** [comment]
@maringan Why have you closed the PR? I would be glad to merge you improvement.

**Comment by maringan** [comment]
@lreimer Hi I would like to fix tow issues from gitmagic, but I can't do this now

**Comment by maringan** [comment]
@lreimer Hi I would like to fix tow issues from gitmagic, but I can't do this now

**Comment by lreimer** [comment]
I understand. Do not worry about the GitMagic Bot too much, I may need o adjust the level it complains about, it is an experiment :)

So if you are happy with the change and it works, leave the PR open, and I will merge the changes later today.

**Comment by maringan** [comment]
@lreimer Hi! I fixed GitMagic issues. Cloud you check PR and merge it if everything is fine?

**Pull request merged**
